/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { Text, useGLTF } from "@react-three/drei";
import { motion } from "framer-motion-3d"
import model from './honeycomb.gltf'
import font from "./font.ttf"

export default function Honeycomb(props) {
  const { nodes, materials } = useGLTF(model);
  const comb = useRef()
  return (
    <group dispose={null}>
      <motion.mesh name={`item${props.id}`}
      castShadow
      receiveShadow
      animate={{ rotateY: 180, type: "spring", swiftness: 1 }}
      transition={{ ease: "linear", duration: props.animDuration, repeat: Infinity }}
      geometry={nodes.honeycomb.geometry}
      material={materials.pintura_basica}
      rotation={[0, 0, -Math.PI / 2]}
      scale={props.scale}
      position={props.position}
      />

      <Text ref={comb}
      scale={.02}
      fontSize={16}
      maxWidth={150}
      textAlign="center"
      anchorX={"center"}
      anchorY={"middle"}
      position={[0.1,.68,0]}
      outlineOffsetX={'0%'}
      outlineOffsetY={'4%'}
      outlineBlur={2}
      outlineOpacity={0.8}
      letterSpacing={.06}
      lineHeight={1.4}
      outlineColor="#000000"
      font={font}
      color={"#FFF"}
      >
      Desenvolvimento de software personalizado
      </Text>

      <Text ref={comb}
      scale={.02}
      fontSize={10}
      maxWidth={150}
      textAlign="center"
      anchorX={"center"}
      anchorY={"middle"}
      position={[0.1,-.8,0]}
      outlineOffsetX={'0%'}
      outlineOffsetY={'4%'}
      outlineBlur={2}
      outlineOpacity={0.8}
      letterSpacing={.06}
      lineHeight={1.2}
      outlineColor="#000000"
      font={font}
      color={"#FFF"}
      >
      Nosso trabalho é desenvolver soluções que podem potencializar o seu negócio.
      </Text>
    </group>
  );
}

useGLTF.preload("/honeycomb.gltf");
