/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { Environment, Stars, Text, useGLTF } from "@react-three/drei";
import { motion } from "framer-motion-3d"
import model from './honeycomb1.gltf'
import font from "./font.ttf"

export default function Honeycomb(props) {
  const { nodes } = useGLTF(model);
  const comb = useRef()

  const container = {
    hidden:{x:0},
    show:{
      x:0,
      transition:{
        duration:1.5,
        staggerChildren: 0.5,
      }
    }
  }

  const item = {
    hidden:{x:-100},
    show:{
      x:0,
      transition:{
        type:'spring',
        bounce:0.1,
        duration:2.5,
        mass: .4
      }
    }
  }

  return (
    <motion.group dispose={null}>
      <Stars count={1000} factor={16} fade={true} depth={100} />
      <Environment preset="night" background={1} blur={.06} resolution={.5}/>
      <motion.mesh name={`item${props.id}`}
      castShadow
      receiveShadow
      animate={{ rotateY: 360, type: "spring", swiftness: 2000 }}
      transition={{ ease: "linear", duration: props.animDuration, repeat: Infinity }}
      geometry={nodes.honeycomb.geometry}
      initial={{rotateY:180}}
      rotation={[0, 0, -Math.PI / 2]}
      scale={props.scale}
      position={props.position}
      >
        <meshStandardMaterial metalness={.8} roughness={.05} color={'#FFFF00'} fog={true}/>
      </motion.mesh>

      <motion.group variants={container} initial="hidden" animate="show" dispose={null}>
        <motion.group variants={item}>
          <Text ref={comb}
          scale={.02}
          fontSize={20}
          maxWidth={150}
          letterSpacing={.1}
          lineHeight={1}
          textAlign="center"
          anchorX={"center"}
          anchorY={"middle"}
          position={[0,.68,(props.planeScale - 1.5)]}
          outlineOffsetX={'0%'}
          outlineOffsetY={'4%'}
          outlineBlur={2}
          outlineOpacity={0.8}
          outlineColor="#000000"
          // font={font}
          color={"#FF0"}
          receiveShadow
          castShadow
          >
          Desenvolvimento de software personalizado
          </Text>
        </motion.group>

        <motion.group variants={item}>
          <Text ref={comb}
          scale={.02}
          fontSize={10}
          maxWidth={180}
          textAlign="center"
          anchorX={"center"}
          anchorY={"middle"}
          position={[0,-.5,(props.planeScale - 1)]}
          outlineOffsetX={'0%'}
          outlineOffsetY={'4%'}
          outlineBlur={2}
          outlineOpacity={0.8}
          letterSpacing={.02}
          lineHeight={1.2}
          outlineColor="#000000"
          font={font}
          color={"#FFF"}
          receiveShadow
          castShadow
          >
          Soluções que podem potencializar o seu negócio.
          </Text>
        </motion.group>

      </motion.group>

      <Text ref={comb}
      scale={.03}
      fontSize={10}
      maxWidth={150}
      textAlign="center"
      anchorX={"center"}
      anchorY={"middle"}
      position={[0,-1.3,props.greetingsScale - 1.5]}
      outlineOffsetX={'0%'}
      outlineOffsetY={'4%'}
      outlineBlur={2}
      outlineOpacity={0.8}
      letterSpacing={.02}
      lineHeight={1.2}
      outlineColor="#000000"
      font={font}
      color={"#FF0"}
      receiveShadow
      castShadow
      >
      Seja bem-vindo!
      </Text>
    </motion.group>
  );
}

useGLTF.preload("/honeycomb1.gltf");
